In [1]:
import numpy as np

In [2]:
x = (1/2) * np.pi
matrix = np.array([[np.cos(x), -np.sin(x)], 
                   [np.sin(x), np.cos(x)]])

print(matrix)

[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]


In [3]:
mT = matrix.T
mInv = np.linalg.inv(matrix)

print(mT)
print(mInv)

[[ 6.123234e-17  1.000000e+00]
 [-1.000000e+00  6.123234e-17]]
[[ 6.123234e-17  1.000000e+00]
 [-1.000000e+00  6.123234e-17]]


In [4]:
dot1 = np.dot(matrix, mInv)
dot2 = np.dot(mInv, matrix)

print(dot1)
print(dot2)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
